/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Pointa Labs. All rights reserved.
 *  Licensed under the Apache License, Version 2.0. See LICENSE in the repository root.
 *--------------------------------------------------------------------------------------------*/

/**
 * Checked-in fixture of the agent-guide sections earlier BaseHalf versions
 * wrote into a workspace's `CLAUDE.md`, `AGENTS.md`, and
 * `.github/copilot-instructions.md`, taken verbatim from git history.
 *
 * Each entry is the text from its marker line to the end of the file, as the
 * installer wrote it. Open-marker-only and recall-hint sections ran to the end
 * of the file, so legacy cleanup may only remove such a section when its text
 * equals (or starts with) one of these bodies. Closed-section bodies (from
 * installers that also wrote `<!-- /bh:workspace-hint -->`) are included for
 * a file whose close marker was later deleted.
 *
 * Sources are `<path>@<commit> (<date>; <form>[; shipped in <tags>])`. Do not
 * edit these bodies by hand: they must stay byte-identical to what shipped.
 */
export interface IBaseHalfLegacyAgentGuideSection {
	readonly marker: 'workspace-hint' | 'recall-hint';
	readonly sources: readonly string[];
	/** The section's lines, marker line first; joined with `\n` plus a final `\n`. */
	readonly lines: readonly string[];
}

export const BASEHALF_LEGACY_AGENT_GUIDE_SECTIONS: readonly IBaseHalfLegacyAgentGuideSection[] = [
	{
		marker: 'recall-hint',
		sources: [
			'packages/core/src/modules/workspace/setup.ts@ad92b728d (2026-05-27; open-only)'
		],
		lines: [
			'<!-- bh:recall-hint -->',
			'## Using `bh` (BaseHalf)',
			'',
			'Before answering non-trivial design / "why did we\u2026" questions, run:',
			'',
			'```bash',
			'bh decision recall --json',
			'```',
			'',
			'Cite slugs + rationale + sources in your answer. If recall surfaces nothing',
			'relevant, offer to record a new decision with `bh decision add`.'
		]
	},
	{
		marker: 'workspace-hint',
		sources: [
			'packages/core/src/modules/workspace/setup.ts@d65236d9c (2026-05-28; open-only)'
		],
		lines: [
			'<!-- bh:workspace-hint -->',
			'## BaseHalf workspace',
			'',
			'This folder is a BaseHalf workspace. BaseHalf is a local-first canvas +',
			'block editor; you (the AI agent) read its metadata under `.bh/` to',
			'understand what the user is focused on and how their files relate, then',
			'compose context from there.',
			'',
			'### Start every turn here',
			'',
			'Read `.bh/focus.md`. It is a small Markdown file with a YAML-style',
			'`active:` list of workspace-relative paths the user is currently focused',
			'on (the desktop UI updates it as the user clicks badges). Treat it as the',
			'"what should I be paying attention to right now" signal.',
			'',
			'### Per-file context (the "backpack")',
			'',
			'For each file in `active:`, read its badge JSON:',
			'',
			'- `.bh/badges/<rel-path>.json` for files',
			'- `.bh/badges/<rel-path>/.badge.json` for folders',
			'',
			'Badge shape:',
			'',
			'```json',
			'{',
			'  "file": "intro.md",',
			'  "kind": "file",',
			'  "prompt": "What the user wants you to know about this file",',
			'  "references": [',
			'    { "to": "overview.md", "note": "why this one points at that one" }',
			'  ]',
			'}',
			'```',
			'',
			'Follow `references` to walk the neighborhood \u2014 the user has explicitly',
			'said "these things go together."',
			'',
			'### Reverse index + saved views',
			'',
			'- `.bh/index/inbound.json` \u2014 who points AT a given file. Use to surface',
			'  related context the user has connected from elsewhere.',
			'- `.bh/views/<id>.json` \u2014 named cross-folder groupings. If the user',
			'  mentions a view by name, read its members to scope your context.',
			'',
			'### Constraints',
			'',
			'- **MD is the truth.** User content lives in `.md` and other source',
			'  files. `.bh/` is derived metadata only. Edit user files with your own',
			'  tools; never edit `.bh/*.json` directly \u2014 the desktop app and `bh`',
			'  CLI own that surface.',
			'- **`.bh/cache/` is rebuildable** and gitignored. Don\'t read or write to',
			'  it.',
			'- `bh` CLI reads accept `--json` for stable output (`bh --help`).'
		]
	},
	{
		marker: 'workspace-hint',
		sources: [
			'packages/core/src/modules/workspace/setup.ts@2773b1a5b (2026-05-28; open-only)'
		],
		lines: [
			'<!-- bh:workspace-hint -->',
			'## BaseHalf workspace',
			'',
			'This folder is registered as a BaseHalf workspace. BaseHalf stores its',
			'metadata under `.bh/` (kept alongside your files so it travels with the',
			'folder; only `.bh/cache/` is gitignored since it\'s rebuildable).',
			'',
			'The desktop app (canvas + block editor + agent protocol) is in active',
			'development. Once it ships, this hint will be replaced by a full agent',
			'protocol guide. For now, the available `bh` operations are workspace',
			'management \u2014 see `bh workspace --help`.'
		]
	},
	{
		marker: 'workspace-hint',
		sources: [
			'packages/core/src/modules/workspace/setup.ts@b4b86b615 (2026-05-30; open-only)',
			'packages/core/src/modules/workspace/setup.ts@bb32c895b (2026-05-30; open-only)',
			'packages/core/src/modules/workspace/setup.ts@95954b27a (2026-05-30; open-only)'
		],
		lines: [
			'<!-- bh:workspace-hint -->',
			'## BaseHalf workspace',
			'',
			'This folder is a BaseHalf workspace. BaseHalf is a local-first canvas +',
			'block editor; you (the AI agent) read its metadata under `.bh/` to',
			'understand what the user is focused on and how their files relate, then',
			'compose context from there.',
			'',
			'### Start every turn here',
			'',
			'Read `.bh/focus.md`. The desktop UI rewrites it as the user clicks badges,',
			'and it is a **self-contained turn brief** \u2014 not just a list of paths. One',
			'read gives you the user\'s curated meaning:',
			'',
			'- `intent:` (optional) \u2014 what the user is trying to do this turn (carried',
			'  from a focused task or a saved view\'s prompt).',
			'- `active:` \u2014 the workspace-relative paths the user is focused on right',
			'  now, and inlined under each: its `prompt:` (what the user wants you to',
			'  know about that file) and its outbound `refs:` with notes (which files',
			'  they\'ve said go together, and why).',
			'',
			'Because the prompts and reference-notes are inlined, focus.md is usually all',
			'you need to know what to pay attention to \u2014 you do NOT have to open each',
			'active file\'s badge JSON just to recover them.',
			'',
			'### Go deeper when the brief isn\'t enough',
			'',
			'`.bh/` holds the full graph behind focus.md. Reach for it to follow a',
			'reference outward or pull in context the user connected from elsewhere:',
			'',
			'- `.bh/badges/<rel-path>.json` (files) / `.bh/badges/<rel-path>/.badge.json`',
			'  (folders) \u2014 the full "backpack" for ANY file, including ones not in',
			'  `active:` that you reach by following a reference. Shape:',
			'',
			'```json',
			'{',
			'  "file": "intro.md",',
			'  "kind": "file",',
			'  "prompt": "What the user wants you to know about this file",',
			'  "references": [',
			'    { "to": "overview.md", "note": "why this one points at that one" }',
			'  ]',
			'}',
			'```',
			'',
			'- `.bh/index/inbound.json` \u2014 who points AT a given file. Use it to surface',
			'  related context the user has connected from elsewhere.',
			'- `.bh/views/<id>.json` \u2014 named cross-folder groupings. If the user',
			'  mentions a view by name, read its members to scope your context.',
			'',
			'### Constraints',
			'',
			'- **MD is the truth.** User content lives in `.md` and other source',
			'  files. `.bh/` is derived metadata only. Edit user files with your own',
			'  tools; never edit `.bh/*.json` directly \u2014 the desktop app and `bh`',
			'  CLI own that surface.',
			'- **`.bh/cache/` is rebuildable** and gitignored. Don\'t read or write to',
			'  it.',
			'- `bh` CLI reads accept `--json` for stable output (`bh --help`).'
		]
	},
	{
		marker: 'workspace-hint',
		sources: [
			'packages/core/src/modules/workspace/setup.ts@823b4fd05 (2026-06-01; open-only)'
		],
		lines: [
			'<!-- bh:workspace-hint -->',
			'## BaseHalf workspace',
			'',
			'This folder is a BaseHalf workspace. BaseHalf is a local-first canvas +',
			'block editor; you (the AI agent) read its metadata under `.bh/` to',
			'understand what the user is focused on and how their files relate, then',
			'compose context from there.',
			'',
			'### Start every turn here',
			'',
			'Read `.bh/focus.md`. The desktop UI rewrites it as the user clicks badges,',
			'and it is a **self-contained turn brief** \u2014 not just a list of paths. One',
			'read gives you the user\'s curated meaning:',
			'',
			'- `intent:` (optional) \u2014 what the user is trying to do this turn (carried',
			'  from a focused task or a saved view\'s prompt).',
			'- `active:` \u2014 the workspace-relative paths the user is focused on right',
			'  now, and inlined under each: its `prompt:` (what the user wants you to',
			'  know about that file) and its outbound `refs:` with notes (which files',
			'  they\'ve said go together, and why).',
			'',
			'Because the prompts and reference-notes are inlined, focus.md is usually all',
			'you need to know what to pay attention to \u2014 you do NOT have to open each',
			'active file\'s badge JSON just to recover them.',
			'',
			'### Go deeper when the brief isn\'t enough',
			'',
			'`.bh/` holds the full graph behind focus.md. Reach for it to follow a',
			'reference outward or pull in context the user connected from elsewhere:',
			'',
			'- `.bh/badges/<rel-path>.json` (files) / `.bh/badges/<rel-path>/.badge.json`',
			'  (folders) \u2014 the full "backpack" for ANY file, including ones not in',
			'  `active:` that you reach by following a reference. Shape:',
			'',
			'```json',
			'{',
			'  "file": "intro.md",',
			'  "kind": "file",',
			'  "prompt": "What the user wants you to know about this file",',
			'  "references": [',
			'    { "to": "overview.md", "note": "why this one points at that one" }',
			'  ]',
			'}',
			'```',
			'',
			'- `.bh/index/inbound.json` \u2014 who points AT a given file. Use it to surface',
			'  related context the user has connected from elsewhere.',
			'',
			'### Constraints',
			'',
			'- **MD is the truth.** User content lives in `.md` and other source',
			'  files. `.bh/` is derived metadata only. Edit user files with your own',
			'  tools; never edit `.bh/*.json` directly \u2014 the desktop app and `bh`',
			'  CLI own that surface.',
			'- **`.bh/cache/` is rebuildable** and gitignored. Don\'t read or write to',
			'  it.',
			'- `bh` CLI reads accept `--json` for stable output (`bh --help`).'
		]
	},
	{
		marker: 'workspace-hint',
		sources: [
			'packages/core/src/modules/workspace/setup.ts@e1e53826c (2026-06-07; open-only)'
		],
		lines: [
			'<!-- bh:workspace-hint -->',
			'## BaseHalf workspace',
			'',
			'This folder is a BaseHalf workspace. **At the start of every turn, read',
			'`.bh/focus.md`** \u2014 a self-contained turn brief the app keeps fresh (it never points',
			'at a deleted file). It carries an optional `intent:` (what the user is doing this',
			'turn) and an `active:` list of the files they\'re focused on, each with its',
			'`prompt:` (what they want you to know) and `refs:` (which files connect, and why).',
			'One read gives you the user\'s curated attention \u2014 grep can\'t recover those',
			'human-written notes.',
			'',
			'Need more than the brief? The full graph is under `.bh/`:',
			'`.bh/badges/<rel-path>.json` is any file\'s backpack (prompt + references), and',
			'`.bh/index/inbound.json` is who points AT a file. Follow these on your own budget.',
			'',
			'MD is the truth; `.bh/` is derived \u2014 edit user files with your own tools,',
			'never `.bh/*` (the app and `bh` CLI own it; `.bh/cache/` is rebuildable and',
			'gitignored). `bh` CLI reads accept `--json`.'
		]
	},
	{
		marker: 'workspace-hint',
		sources: [
			'packages/core/src/modules/workspace/setup.ts@fa18a5fc7 (2026-06-09; open-only)'
		],
		lines: [
			'<!-- bh:workspace-hint -->',
			'## BaseHalf workspace',
			'',
			'This folder is a BaseHalf workspace. **At the start of every turn, read',
			'`.bh/focus.md`** \u2014 a self-contained turn brief the app keeps fresh (it never points',
			'at a deleted file). It carries an optional `intent:` (what the user is doing this',
			'turn) and an `active:` list of the files they\'re focused on, each with its',
			'`prompt:` (what they want you to know) and `refs:` (which files connect, and why).',
			'One read gives you the user\'s curated attention \u2014 grep can\'t recover those',
			'human-written notes.',
			'',
			'Need more than the brief? Read the graph under `.bh/` directly, or \u2014 if you have a',
			'shell \u2014 drive the `bh` CLI (reads accept `--json`):',
			'- `.bh/badges/<rel-path>.json` \u2014 any file\'s backpack (prompt + references); or `bh badge get <path> --json`',
			'- `.bh/index/inbound.json` \u2014 who points AT a file; or `bh inbound get <path> --json`',
			'- `bh search <query> --json` \u2014 full-text search across the workspace\'s text files',
			'',
			'MD is the truth; `.bh/` is derived \u2014 edit user files with your own tools,',
			'never `.bh/*` (the app and `bh` CLI own it; `.bh/cache/` is rebuildable and',
			'gitignored).'
		]
	},
	{
		marker: 'workspace-hint',
		sources: [
			'packages/core/src/modules/workspace/setup.ts@a41326359 (2026-06-12; open-only; shipped in v0.2.0, v0.2.1)'
		],
		lines: [
			'<!-- bh:workspace-hint -->',
			'## BaseHalf workspace',
			'',
			'This folder is a BaseHalf workspace. **At the start of every turn, read',
			'`.bh/focus.md`** \u2014 a self-contained turn brief the app keeps fresh (it never points',
			'at a deleted file). It carries an optional `intent:` (what the user is doing this',
			'turn) and an `active:` list of the files they\'re focused on, each with its',
			'`prompt:` (what they want you to know) and `refs:` (which files connect, and why).',
			'One read gives you the user\'s curated attention \u2014 grep can\'t recover those',
			'human-written notes.',
			'',
			'Need more than the brief? Read the graph under `.bh/` directly, or \u2014 if you have a',
			'shell \u2014 drive the `bh` CLI (reads accept `--json`):',
			'- `.bh/badges/<rel-path>.json` \u2014 any file\'s backpack (prompt + references); or `bh badge get <path> --json`',
			'- `.bh/index/inbound.json` \u2014 who points AT a file; or `bh inbound get <path> --json`',
			'- `bh search <query> --json` \u2014 full-text search across the workspace\'s text files',
			'- `bh search <query> --brief` \u2014 assemble a paste-ready context brief from the matches (each hydrated with its prompt + reference notes)',
			'',
			'While working, if you discover a file relationship or a key fact that no badge',
			'note records (e.g. "touching X breaks Y\'s test"), append one line to',
			'`.bh/cache/proposals.md`: `[file] -> [target or fact]: [reason]`. The user',
			'triages these into real notes.',
			'',
			'MD is the truth; `.bh/` is derived \u2014 edit user files with your own tools,',
			'never `.bh/*` (the app and `bh` CLI own it; the proposals file above is the',
			'ONE exception). `.bh/cache/` is gitignored; it is rebuildable EXCEPT the',
			'proposals file, which holds your observations.'
		]
	},
	{
		marker: 'workspace-hint',
		sources: [
			'packages/core/src/modules/workspace/setup.ts@0ebd96d81 (2026-06-12; open-only)',
			'packages/core/src/modules/workspace/setup.ts@89c885bbe (2026-06-12; open-only)'
		],
		lines: [
			'<!-- bh:workspace-hint -->',
			'## BaseHalf workspace',
			'',
			'This folder is a BaseHalf workspace. **At the start of every turn, read',
			'`.bh/focus.md`** \u2014 a self-contained turn brief the app keeps fresh (it never points',
			'at a deleted file). It carries an optional `intent:` (what the user is doing this',
			'turn) and an `active:` list of the files they\'re focused on, each with its',
			'`prompt:` (what they want you to know) and `refs:` (which files connect, and why).',
			'One read gives you the user\'s curated attention \u2014 grep can\'t recover those',
			'human-written notes.',
			'',
			'Need more than the brief? Read the graph under `.bh/` directly, or \u2014 if you have a',
			'shell \u2014 drive the `bh` CLI (reads accept `--json`):',
			'- `.bh/badges/<rel-path>.json` \u2014 any file\'s backpack (prompt + references); or `bh badge get <path> --json`',
			'- `.bh/index/inbound.json` \u2014 who points AT a file; or `bh inbound get <path> --json`',
			'- `bh search <query> --json` \u2014 full-text search across the workspace\'s text files',
			'- `bh search <query> --brief` \u2014 assemble a paste-ready context brief from the matches (each hydrated with its prompt + reference notes)',
			'',
			'MD is the truth; `.bh/` is derived \u2014 edit user files with your own tools,',
			'never `.bh/*` (the app and `bh` CLI own it; `.bh/cache/` is rebuildable and',
			'gitignored).'
		]
	},
	{
		marker: 'workspace-hint',
		sources: [
			'packages/core/src/modules/workspace/setup.ts@4aada84f2 (2026-06-13; closed (close marker removed); shipped in v0.2.4)'
		],
		lines: [
			'<!-- bh:workspace-hint -->',
			'## BaseHalf workspace',
			'',
			'> Added by [BaseHalf](https://github.com/Pointa-Labs/basehalf) when this folder',
			'> was opened as a workspace \u2014 it tells AI coding agents where the user\'s',
			'> curated context lives. Your own content above/below is untouched; delete',
			'> this section if you don\'t want agents reading that context.',
			'',
			'This folder is a BaseHalf workspace. **At the start of every turn, read',
			'`.bh/focus.md`** \u2014 a self-contained turn brief the app keeps fresh (it never points',
			'at a deleted file). It carries an optional `intent:` (what the user is doing this',
			'turn) and an `active:` list of the files they\'re focused on, each with its',
			'`prompt:` (what they want you to know) and `refs:` (which files connect, and why).',
			'One read gives you the user\'s curated attention \u2014 grep can\'t recover those',
			'human-written notes.',
			'',
			'Need more than the brief? Read the graph under `.bh/` directly, or \u2014 if you have a',
			'shell \u2014 drive the `bh` CLI (reads accept `--json`):',
			'- `.bh/badges/<rel-path>.json` \u2014 any file\'s backpack (prompt + references); or `bh badge get <path> --json`',
			'- `.bh/index/inbound.json` \u2014 who points AT a file; or `bh inbound get <path> --json`',
			'- `bh search <query> --json` \u2014 full-text search across the workspace\'s text files',
			'- `bh search <query> --brief` \u2014 assemble a paste-ready context brief from the matches (each hydrated with its prompt + reference notes)',
			'',
			'If you have a shell, read the brief with `bh focus brief` instead of opening the',
			'file: it returns the same content AND records that the brief was delivered, so the',
			'app can tell the user their context reached you (a raw file read is invisible to it).',
			'',
			'While working, if you discover a file relationship or a key fact that no badge',
			'note records (e.g. "touching X breaks Y\'s test"), append one line to',
			'`.bh/cache/proposals.md`: `[file] -> [target or fact]: [reason]`. The user',
			'triages these into real notes.',
			'',
			'MD is the truth; `.bh/` is derived \u2014 edit user files with your own tools,',
			'never `.bh/*` (the app and `bh` CLI own it; the proposals file above is the',
			'ONE exception). `.bh/cache/` is gitignored; it is rebuildable EXCEPT the',
			'proposals file, which holds your observations.'
		]
	},
	{
		marker: 'workspace-hint',
		sources: [
			'packages/core/src/modules/workspace/setup.ts@a0677df3e (2026-06-13; open-only; shipped in v0.2.2, v0.2.3)'
		],
		lines: [
			'<!-- bh:workspace-hint -->',
			'## BaseHalf workspace',
			'',
			'> Added by [BaseHalf](https://github.com/Pointa-Labs/basehalf) when this folder',
			'> was opened as a workspace \u2014 it tells AI coding agents where the user\'s',
			'> curated context lives. Your own content above/below is untouched; delete',
			'> this section if you don\'t want agents reading that context.',
			'',
			'This folder is a BaseHalf workspace. **At the start of every turn, read',
			'`.bh/focus.md`** \u2014 a self-contained turn brief the app keeps fresh (it never points',
			'at a deleted file). It carries an optional `intent:` (what the user is doing this',
			'turn) and an `active:` list of the files they\'re focused on, each with its',
			'`prompt:` (what they want you to know) and `refs:` (which files connect, and why).',
			'One read gives you the user\'s curated attention \u2014 grep can\'t recover those',
			'human-written notes.',
			'',
			'Need more than the brief? Read the graph under `.bh/` directly, or \u2014 if you have a',
			'shell \u2014 drive the `bh` CLI (reads accept `--json`):',
			'- `.bh/badges/<rel-path>.json` \u2014 any file\'s backpack (prompt + references); or `bh badge get <path> --json`',
			'- `.bh/index/inbound.json` \u2014 who points AT a file; or `bh inbound get <path> --json`',
			'- `bh search <query> --json` \u2014 full-text search across the workspace\'s text files',
			'- `bh search <query> --brief` \u2014 assemble a paste-ready context brief from the matches (each hydrated with its prompt + reference notes)',
			'',
			'While working, if you discover a file relationship or a key fact that no badge',
			'note records (e.g. "touching X breaks Y\'s test"), append one line to',
			'`.bh/cache/proposals.md`: `[file] -> [target or fact]: [reason]`. The user',
			'triages these into real notes.',
			'',
			'MD is the truth; `.bh/` is derived \u2014 edit user files with your own tools,',
			'never `.bh/*` (the app and `bh` CLI own it; the proposals file above is the',
			'ONE exception). `.bh/cache/` is gitignored; it is rebuildable EXCEPT the',
			'proposals file, which holds your observations.'
		]
	},
	{
		marker: 'workspace-hint',
		sources: [
			'packages/core/src/modules/workspace/setup.ts@3c6215d7e (2026-06-17; closed (close marker removed))'
		],
		lines: [
			'<!-- bh:workspace-hint -->',
			'## BaseHalf workspace',
			'',
			'> Added by [BaseHalf](https://github.com/Pointa-Labs/basehalf) when this folder',
			'> was opened as a workspace \u2014 it tells AI coding agents what the user is looking',
			'> at. Your own content above/below is untouched; delete this section if you don\'t',
			'> want agents reading that context.',
			'',
			'This folder is a BaseHalf workspace: BaseHalf mirrors what the user is currently',
			'viewing into `.bh/` so you stay in sync with their attention.',
			'',
			'**At the start of every turn, read `.bh/current_focus.yaml`** \u2014 a symlink to the',
			'focus file of the node the user is looking at right now:',
			'- `kind: file` \u2192 they\'re reading a file. Use the file\'s content together with its',
			'  `badge.yaml`, plus `visible_lines.start` and `cursor` (where they are in it).',
			'- `kind: folder` \u2192 they\'re on a folder\'s canvas. Use that folder\'s `badge.yaml`',
			'  and `canvas.yaml`, plus `viewport_center` and `zoom`.',
			'',
			'The `.bh/mirror/` tree holds up to four YAML files per node (sparse \u2014 only what\'s',
			'been annotated):',
			'- `.bh/mirror/<path>/badge.yaml` \u2014 a node\'s one-line `description`, outbound',
			'  `references` (paths) and inbound `referenced_by` (paths).',
			'- `.bh/mirror/<folder>/canvas.yaml` \u2014 a folder\'s canvas: child card positions and',
			'  `edges` (connections with anchors + labels) between them.',
			'- `.bh/mirror/<path>/focus.yaml` \u2014 a node\'s viewport (`current_focus` points at',
			'  the live one).',
			'- `.bh/mirror/<file>/adhd.yaml` \u2014 per-file reading aids: `highlight_keywords` and',
			'  read line-ranges (`read_paragraphs`).',
			'',
			'To answer or edit, start from the focused node, then follow its `references` /',
			'`referenced_by` and the `canvas.yaml` structure for context. Only modify the',
			'user\'s own files when they explicitly ask.',
			'',
			'When asked, you can GENERATE or update these `.bh/` files from content (a',
			'badge.yaml/canvas.yaml for a folder, an adhd.yaml for a file). Match the existing',
			'YAML shape; read the latest version before editing so you don\'t overwrite what the',
			'app or the user just wrote; don\'t store anything derivable from paths, line numbers,',
			'or the reference graph. `.bh/current_focus.yaml` is a symlink \u2014 never replace it',
			'with a regular file.',
			'',
			'The user\'s files are the source of truth; `.bh/` is derived. Edit user files with',
			'your own tools; the app owns `.bh/`. `.bh/cache/` is gitignored and rebuildable;',
			'the rest of `.bh/` stays in git so the map travels with the folder.'
		]
	},
	{
		marker: 'workspace-hint',
		sources: [
			'packages/core/src/modules/workspace/setup.ts@49c38de9e (2026-06-19; closed (close marker removed); shipped in v0.3.0, v0.3.1, v0.3.2, v0.3.3)'
		],
		lines: [
			'<!-- bh:workspace-hint -->',
			'## BaseHalf workspace',
			'',
			'> Added by [BaseHalf](https://github.com/Pointa-Labs/basehalf) when this folder',
			'> was opened as a workspace \u2014 it tells AI coding agents what the user is looking',
			'> at. Your own content above/below is untouched; delete this section if you don\'t',
			'> want agents reading that context.',
			'',
			'This folder is a BaseHalf workspace: BaseHalf mirrors what the user is currently',
			'viewing into `.bh/` so you stay in sync with their attention.',
			'',
			'**At the start of every turn, read `.bh/current_focus.yaml`** \u2014 a symlink to the',
			'focus file of the node the user is looking at right now:',
			'- `kind: file` \u2192 they\'re reading a file. Use the file\'s content together with its',
			'  `badge.yaml`, plus `visible_lines.start` / `visible_blocks.start` and `cursor`. In',
			'  `cursor`, `line`/`column` are 1-based positions in the .md SOURCE (use them to',
			'  locate/edit) and `line_precision` says how exact `line` is (`exact` |',
			'  `block_start` | `estimated`); `block` is the ordinal of the rendered block they\'re',
			'  in \u2014 the "Nth block" they actually see. Blank lines and multi-line blocks make the',
			'  source line exceed the block count, so prefer `block` (and `visible_blocks`) when',
			'  describing where the user is.',
			'- `kind: folder` \u2192 they\'re on a folder\'s canvas. Use that folder\'s `badge.yaml`',
			'  and `canvas.yaml`, plus `viewport_center` and `zoom`.',
			'',
			'The `.bh/mirror/` tree holds up to four YAML files per node (sparse \u2014 only what\'s',
			'been annotated):',
			'- `.bh/mirror/<path>/badge.yaml` \u2014 a node\'s one-line `description`, outbound',
			'  `references` (paths) and inbound `referenced_by` (paths).',
			'- `.bh/mirror/<folder>/canvas.yaml` \u2014 a folder\'s canvas: child card positions and',
			'  `edges` (connections with anchors + labels) between them.',
			'- `.bh/mirror/<path>/focus.yaml` \u2014 a node\'s viewport (`current_focus` points at',
			'  the live one).',
			'- `.bh/mirror/<file>/adhd.yaml` \u2014 per-file reading aids: `highlight_keywords` and',
			'  read line-ranges (`read_paragraphs`).',
			'',
			'To answer or edit, start from the focused node, then follow its `references` /',
			'`referenced_by` and the `canvas.yaml` structure for context. Only modify the',
			'user\'s own files when they explicitly ask.',
			'',
			'When asked, you can GENERATE or update these `.bh/` files from content (a',
			'badge.yaml/canvas.yaml for a folder, an adhd.yaml for a file). Match the existing',
			'YAML shape; read the latest version before editing so you don\'t overwrite what the',
			'app or the user just wrote; don\'t store anything derivable from paths, line numbers,',
			'or the reference graph. `.bh/current_focus.yaml` is a symlink \u2014 never replace it',
			'with a regular file.',
			'',
			'The user\'s files are the source of truth; `.bh/` is derived. Edit user files with',
			'your own tools; the app owns `.bh/`. `.bh/cache/` is gitignored and rebuildable;',
			'the rest of `.bh/` stays in git so the map travels with the folder.'
		]
	},
	{
		marker: 'workspace-hint',
		sources: [
			'packages/core/src/modules/workspace/setup.ts@aa4c28364 (2026-06-25; closed (close marker removed))'
		],
		lines: [
			'<!-- bh:workspace-hint -->',
			'## BaseHalf workspace',
			'',
			'> Added by [BaseHalf](https://github.com/Pointa-Labs/basehalf) when this folder',
			'> was opened as a workspace \u2014 it tells AI coding agents what the user is looking',
			'> at. Your own content above/below is untouched; delete this section if you don\'t',
			'> want agents reading that context.',
			'',
			'This folder is a BaseHalf workspace: BaseHalf mirrors what the user is currently',
			'viewing into `.bh/` so you stay in sync with their attention.',
			'',
			'**At the start of every turn, read `.bh/current_focus.yaml`** \u2014 a symlink to the',
			'focus file of the node the user is looking at right now:',
			'- `kind: file` \u2192 they\'re reading a file. Use the file\'s content together with its',
			'  `badge.yaml`, plus `visible_lines.start` / `visible_blocks.start` and `cursor`. In',
			'  `cursor`, `line`/`column` are 1-based positions in the .md SOURCE (use them to',
			'  locate/edit) and `line_precision` says how exact `line` is (`exact` |',
			'  `block_start` | `estimated`); `block` is the ordinal of the rendered block they\'re',
			'  in \u2014 the "Nth block" they actually see. Blank lines, multi-line blocks, and',
			'  soft-wrapped long lines mean a source line is **not** the user\'s on-screen line \u2014 so',
			'  use `block`/`visible_blocks` to say where they are, and `line`+`column` to',
			'  locate/edit; never hand the user a whole source line as "the line on your screen".',
			'- `kind: folder` \u2192 they\'re on a folder\'s canvas. Use that folder\'s `badge.yaml`',
			'  and `canvas.yaml`, plus `viewport_center` and `zoom`.',
			'',
			'The `.bh/mirror/` tree holds up to four YAML files per node (sparse \u2014 only what\'s',
			'been annotated):',
			'- `.bh/mirror/<path>/badge.yaml` \u2014 a node\'s one-line `description`, outbound',
			'  `references` (paths) and inbound `referenced_by` (paths).',
			'- `.bh/mirror/<folder>/canvas.yaml` \u2014 a folder\'s canvas: child card positions and',
			'  `edges` (connections with anchors + labels) between them.',
			'- `.bh/mirror/<path>/focus.yaml` \u2014 a node\'s viewport (`current_focus` points at',
			'  the live one).',
			'- `.bh/mirror/<file>/adhd.yaml` \u2014 per-file reading aids: `highlight_keywords` and',
			'  read line-ranges (`read_paragraphs`).',
			'',
			'To answer or edit, start from the focused node, then follow its `references` /',
			'`referenced_by` and the `canvas.yaml` structure for context. Only modify the',
			'user\'s own files when they explicitly ask.',
			'',
			'When asked, you can GENERATE or update these `.bh/` files from content (a',
			'badge.yaml/canvas.yaml for a folder, an adhd.yaml for a file). Match the existing',
			'YAML shape; read the latest version before editing so you don\'t overwrite what the',
			'app or the user just wrote; don\'t store anything derivable from paths, line numbers,',
			'or the reference graph. `.bh/current_focus.yaml` is a symlink \u2014 never replace it',
			'with a regular file.',
			'',
			'The user\'s files are the source of truth; `.bh/` is derived. Edit user files with',
			'your own tools; the app owns `.bh/`. `.bh/cache/` is gitignored and rebuildable;',
			'the rest of `.bh/` stays in git so the map travels with the folder.'
		]
	},
	{
		marker: 'workspace-hint',
		sources: [
			'packages/core/src/modules/workspace/setup.ts@24b767a22 (2026-07-28; closed (close marker removed))',
			'packages/core/src/modules/workspace/setup.ts@01752c535 (2026-06-26; closed (close marker removed); shipped in v0.4.0, v0.4.1)',
			'packages/desktop/src/platform/workspaces/electron-main/workspaceSetup.ts@e0943d7a7 (2026-06-28; closed (close marker removed); shipped in v0.4.0)',
			'vscode-base/src/vs/workbench/basehalf/common/basehalfWorkspaceSetup.ts@efaad8cfc (2026-07-06; closed (close marker removed))'
		],
		lines: [
			'<!-- bh:workspace-hint -->',
			'## BaseHalf workspace',
			'',
			'> Added by [BaseHalf](https://github.com/Pointa-Labs/basehalf) when this folder',
			'> was opened as a workspace \u2014 it tells AI coding agents what the user is looking',
			'> at. Your own content above/below is untouched; delete this section if you don\'t',
			'> want agents reading that context.',
			'',
			'This folder is a BaseHalf workspace: BaseHalf mirrors what the user is currently',
			'viewing into `.bh/` so you stay in sync with their attention.',
			'',
			'**At the start of every turn, read `.bh/current_focus.yaml`** \u2014 a symlink to the',
			'focus file of the node the user is looking at right now:',
			'- `kind: file` \u2192 they\'re reading a file. Use the file\'s content together with its',
			'  `badge.yaml`, plus `visible_lines.start` / `visible_blocks.start` and `cursor`. In',
			'  `cursor`, `line`/`column` are 1-based positions in the .md SOURCE (use them to',
			'  locate/edit) and `line_precision` says how exact `line` is (`exact` |',
			'  `block_start` | `estimated`); `block` is the ordinal of the rendered block they\'re',
			'  in \u2014 the "Nth block" they actually see. Blank lines, multi-line blocks, and',
			'  soft-wrapped long lines mean a source line is **not** the user\'s on-screen line \u2014 so',
			'  use `block`/`visible_blocks` to say where they are, and `line`+`column` to',
			'  locate/edit; never hand the user a whole source line as "the line on your screen".',
			'- `kind: folder` \u2192 they\'re on a folder\'s canvas. Use that folder\'s `badge.yaml`',
			'  and `canvas.yaml`, plus `viewport_center` and `zoom`.',
			'',
			'The `.bh/mirror/` tree holds up to four YAML files per node (sparse \u2014 only what\'s',
			'been annotated):',
			'- `.bh/mirror/<path>/badge.yaml` \u2014 a node\'s one-line `description`, outbound',
			'  `references` (paths) and inbound `referenced_by` (paths).',
			'- `.bh/mirror/<folder>/canvas.yaml` \u2014 a folder\'s canvas: child card positions and',
			'  `edges` (connections with anchors + labels) between them.',
			'- `.bh/mirror/<path>/focus.yaml` \u2014 a node\'s viewport (`current_focus` points at',
			'  the live one).',
			'- `.bh/mirror/<file>/adhd.yaml` \u2014 per-file reading aids: `highlight_keywords` and',
			'  read line-ranges (`read_paragraphs`).',
			'',
			'To answer or edit, start from the focused node, then follow its `references` /',
			'`referenced_by` and the `canvas.yaml` structure for context. Only modify the',
			'user\'s own files when they explicitly ask.',
			'',
			'When asked, you can GENERATE or update these `.bh/` files from content (a',
			'badge.yaml/canvas.yaml for a folder, an adhd.yaml for a file). Match the existing',
			'YAML shape; read the latest version before editing so you don\'t overwrite what the',
			'app or the user just wrote; don\'t store anything derivable from paths, line numbers,',
			'or the reference graph. `.bh/current_focus.yaml` is a symlink \u2014 never replace it',
			'with a regular file.',
			'',
			'For BaseHalf-specific workflows, use `.bh/agent-harness/index.md` as the',
			'progressive-disclosure index. Load only the matching scenario, such as focused-file',
			'rewrites, cursor/viewport questions, or `.bh/` mirror writes, when that behavior',
			'matters.',
			'',
			'The user\'s files are the source of truth; `.bh/` is derived. Edit user files with',
			'your own tools; the app owns `.bh/`. `.bh/cache/` is gitignored and rebuildable;',
			'the rest of `.bh/` stays in git so the map travels with the folder.'
		]
	},
	{
		marker: 'workspace-hint',
		sources: [
			'vscode-base/src/vs/workbench/basehalf/common/basehalfWorkspaceSetup.ts@0e1b74bf3 (2026-07-11; closed (close marker removed); shipped in v0.4.1)'
		],
		lines: [
			'<!-- bh:workspace-hint -->',
			'## BaseHalf workspace',
			'',
			'> Added by [BaseHalf](https://github.com/Pointa-Labs/basehalf) when this folder',
			'> was opened as a workspace \u2014 it tells AI coding agents what the user is looking',
			'> at. Your own content above/below is untouched; delete this section if you don\'t',
			'> want agents reading that context.',
			'',
			'This folder is a BaseHalf workspace: BaseHalf mirrors what the user is currently',
			'viewing into `.bh/` so you stay in sync with their attention.',
			'',
			'**At the start of every turn, read `.bh/current_focus.yaml`** \u2014 a symlink to the',
			'focus file of the node the user is looking at right now:',
			'- `kind: file` \u2192 they\'re reading a file. Use the file\'s content together with its',
			'  `badge.yaml`, plus `visible_lines.start` / `visible_blocks.start` and `cursor`. In',
			'  `cursor`, `line`/`column` are 1-based positions in the .md SOURCE (use them to',
			'  locate/edit) and `line_precision` says how exact `line` is (`exact` |',
			'  `block_start` | `estimated`); `block` is the ordinal of the rendered block they\'re',
			'  in \u2014 the "Nth block" they actually see. Blank lines, multi-line blocks, and',
			'  soft-wrapped long lines mean a source line is **not** the user\'s on-screen line \u2014 so',
			'  use `block`/`visible_blocks` to say where they are, and `line`+`column` to',
			'  locate/edit; never hand the user a whole source line as "the line on your screen".',
			'- `kind: folder` \u2192 they\'re on a folder\'s canvas. Use that folder\'s `badge.yaml`',
			'  and `canvas.yaml`, plus `viewport_center` and `zoom`.',
			'',
			'The `.bh/mirror/` tree holds up to four YAML files per node (sparse \u2014 only what\'s',
			'been annotated):',
			'- `.bh/mirror/<path>/badge.yaml` \u2014 a node\'s one-line `description`, outbound',
			'  `references` (paths) and inbound `referenced_by` (paths). `A \u2192 B` means A\'s',
			'  context flows into B: B is in A\'s `references`, and A is in B\'s `referenced_by`.',
			'  This is a general directed graph, not a tree or parent/child hierarchy.',
			'  A one-sided pair is not live; BaseHalf surfaces it for explicit Repair or Discard.',
			'- `.bh/mirror/<folder>/canvas.yaml` \u2014 a folder\'s canvas: child card positions and',
			'  optional `edges` with endpoints and anchor placement for badge references.',
			'  The badge graph is relationship truth; a canvas edge never creates a separate relation.',
			'- `.bh/mirror/<path>/focus.yaml` \u2014 a node\'s viewport (`current_focus` points at',
			'  the live one).',
			'- `.bh/mirror/<file>/adhd.yaml` \u2014 per-file reading aids: `highlight_keywords` and',
			'  read line-ranges (`read_paragraphs`).',
			'',
			'To answer or edit, start from the focused node. Its incoming `referenced_by` nodes',
			'are upstream context; follow either direction when more graph context is useful.',
			'Markdown links are ordinary navigation links and never create reference edges.',
			'To create a card, create its real user file or folder; a canvas card row stores only',
			'geometry.',
			'Only modify or create the user\'s own files when they explicitly ask.',
			'',
			'When asked, you can GENERATE or update these `.bh/` files from content, including',
			'creating references. Update both badge endpoints; the canvas derives the relation',
			'from that graph. Use `canvas.yaml` only for card geometry and edge endpoints/anchors.',
			'Match the existing YAML shape and read the latest version before editing so you',
			'don\'t overwrite what',
			'the app or user just wrote. `.bh/current_focus.yaml` is a symlink \u2014 never replace',
			'it with a regular file.',
			'',
			'For BaseHalf-specific workflows, use `.bh/agent-harness/index.md` as the',
			'progressive-disclosure index. Load only the matching scenario, such as focused-file',
			'rewrites, cursor/viewport questions, or `.bh/` mirror writes, when that behavior',
			'matters.',
			'',
			'The user\'s files are the source of truth; `.bh/` is derived. Edit user files with',
			'your own tools; edit `.bh/` only on explicit request \u2014 otherwise the app owns it.',
			'`.bh/cache/` is gitignored and rebuildable;',
			'the rest of `.bh/` stays in git so the map travels with the folder.'
		]
	},
	{
		marker: 'workspace-hint',
		sources: [
			'vscode-base/src/vs/workbench/basehalf/common/basehalfWorkspaceSetup.ts@24b767a22 (2026-07-28; closed (close marker removed))',
			'vscode-base/src/vs/workbench/basehalf/common/basehalfWorkspaceSetup.ts@a48c628b5 (2026-07-20; closed (close marker removed))'
		],
		lines: [
			'<!-- bh:workspace-hint -->',
			'## BaseHalf workspace',
			'',
			'> Added by [BaseHalf](https://github.com/Pointa-Labs/basehalf) when this folder',
			'> was opened as a workspace \u2014 it tells AI coding agents what the user is looking',
			'> at. Your own content above/below is untouched; delete this section if you don\'t',
			'> want agents reading that context.',
			'',
			'This folder is a BaseHalf workspace: BaseHalf mirrors what the user is currently',
			'viewing into `.bh/` so you stay in sync with their attention.',
			'',
			'**At the start of every turn, read `.bh/current_focus.yaml`** \u2014 a symlink to the',
			'focus file of the node the user is looking at right now:',
			'- `kind: file` \u2192 they\'re reading a file. Use the file\'s content together with its',
			'  `badge.yaml`, plus `visible_lines.start` / `visible_blocks.start` and `cursor`. In',
			'  `cursor`, `line`/`column` are 1-based positions in the .md SOURCE (use them to',
			'  locate/edit) and `line_precision` says how exact `line` is (`exact` |',
			'  `block_start` | `estimated`); `block` is the ordinal of the rendered block they\'re',
			'  in \u2014 the "Nth block" they actually see. Blank lines, multi-line blocks, and',
			'  soft-wrapped long lines mean a source line is **not** the user\'s on-screen line \u2014 so',
			'  use `block`/`visible_blocks` to say where they are, and `line`+`column` to',
			'  locate/edit; never hand the user a whole source line as "the line on your screen".',
			'- `kind: folder` \u2192 they\'re on a folder\'s canvas. Use that folder\'s `badge.yaml`',
			'  and `canvas.yaml`, plus `viewport_center` and `zoom`.',
			'',
			'The `.bh/mirror/` tree holds up to four YAML files per node (sparse \u2014 only what\'s',
			'been annotated):',
			'- `.bh/mirror/<path>/badge.yaml` \u2014 a node\'s one-line `description`, outbound',
			'  `references` (paths) and inbound `referenced_by` (paths). `A \u2192 B` means A\'s',
			'  context flows into B: B is in A\'s `references`, and A is in B\'s `referenced_by`.',
			'  This is a general directed graph, not a tree or parent/child hierarchy.',
			'  A one-sided pair is not live; BaseHalf surfaces it for explicit Repair or Discard.',
			'- `.bh/mirror/<folder>/canvas.yaml` \u2014 a folder\'s canvas: child card positions and',
			'  optional `edges` with endpoints and anchor placement for badge references.',
			'  The badge graph is relationship truth; a canvas edge never creates a separate relation.',
			'- `.bh/mirror/<path>/focus.yaml` \u2014 a node\'s viewport (`current_focus` points at',
			'  the live one).',
			'- `.bh/mirror/<file>/adhd.yaml` \u2014 per-file reading aids: `highlight_keywords` and',
			'  read line-ranges (`read_paragraphs`).',
			'',
			'To answer or edit, start from the focused node. Its incoming `referenced_by` nodes',
			'are upstream context; follow either direction when more graph context is useful.',
			'Markdown links are ordinary navigation links and never create reference edges.',
			'To create a card, create its real user file or folder; a canvas card row stores only',
			'geometry.',
			'Only modify or create the user\'s own files when they explicitly ask.',
			'',
			'When asked, you can GENERATE or update these `.bh/` files from content, including',
			'creating references. Update both badge endpoints; the canvas derives the relation',
			'from that graph. Use `canvas.yaml` only for card geometry and edge endpoints/anchors.',
			'Match the existing YAML shape and read the latest version before editing so you',
			'don\'t overwrite what',
			'the app or user just wrote. `.bh/current_focus.yaml` is a symlink \u2014 never replace',
			'it with a regular file.',
			'',
			'For BaseHalf-specific workflows, use `.bh/agent-harness/index.md` as the',
			'progressive-disclosure index. Load only the matching scenario, such as focused-file',
			'rewrites, cursor/viewport questions, canvas workflows, or `.bh/` mirror writes,',
			'when that behavior matters.',
			'',
			'The user\'s files are the source of truth; `.bh/` is derived. Edit user files with',
			'your own tools; edit `.bh/` only on explicit request \u2014 otherwise the app owns it.',
			'`.bh/cache/` is gitignored and rebuildable;',
			'the rest of `.bh/` stays in git so the map travels with the folder.'
		]
	},
	{
		marker: 'workspace-hint',
		sources: [
			'vscode-base/src/vs/workbench/basehalf/common/basehalfWorkspaceSetup.ts@d65b453d5 (2026-08-24; closed (close marker removed))',
			'vscode-base/src/vs/workbench/basehalf/common/basehalfWorkspaceSetup.ts@fb00d4aac (2026-08-09; closed (close marker removed))'
		],
		lines: [
			'<!-- bh:workspace-hint -->',
			'## BaseHalf workspace',
			'',
			'> Added by [BaseHalf](https://github.com/Pointa-Labs/basehalf) when this folder',
			'> was opened as a workspace \u2014 it tells AI coding agents what the user is looking',
			'> at. Your own content above/below is untouched; delete this section if you don\'t',
			'> want agents reading that context.',
			'',
			'This folder is a BaseHalf workspace: BaseHalf mirrors what the user is currently',
			'viewing into `.bh/` so you stay in sync with their attention.',
			'',
			'**At the start of every turn, read `.bh/current_focus.yaml`** \u2014 a symlink to the',
			'focus file of the node the user is looking at right now:',
			'- `kind: file` \u2192 they\'re reading a file. Use the file\'s content together with its',
			'  `badge.yaml`, plus `visible_lines.start` / `visible_blocks.start` and `cursor`. In',
			'  `cursor`, `line`/`column` are 1-based positions in the .md SOURCE (use them to',
			'  locate/edit) and `line_precision` says how exact `line` is (`exact` |',
			'  `block_start` | `estimated`); `block` is the ordinal of the rendered block they\'re',
			'  in \u2014 the "Nth block" they actually see. Blank lines, multi-line blocks, and',
			'  soft-wrapped long lines mean a source line is **not** the user\'s on-screen line \u2014 so',
			'  use `block`/`visible_blocks` to say where they are, and `line`+`column` to',
			'  locate/edit; never hand the user a whole source line as "the line on your screen".',
			'- `kind: folder` \u2192 they\'re on a folder\'s canvas. Use that folder\'s `badge.yaml`',
			'  and `canvas.yaml`, plus `viewport_center` and `zoom`.',
			'',
			'The `.bh/mirror/` tree holds up to five YAML files per node (sparse \u2014 only what\'s',
			'been annotated):',
			'- `.bh/mirror/<path>/badge.yaml` \u2014 a node\'s one-line `description`, outbound',
			'  `references` (paths) and inbound `referenced_by` (paths). `A \u2192 B` means A\'s',
			'  context flows into B: B is in A\'s `references`, and A is in B\'s `referenced_by`.',
			'  This is a general directed graph, not a tree or parent/child hierarchy.',
			'  A one-sided pair is not live; BaseHalf surfaces it for explicit Repair or Discard.',
			'- `.bh/mirror/<folder>/canvas.yaml` \u2014 a folder\'s canvas: child card positions and',
			'  optional `edges` with endpoints and anchor placement for badge references.',
			'  The badge graph is relationship truth; a canvas edge never creates a separate relation.',
			'- `.bh/mirror/<path>/focus.yaml` \u2014 a node\'s viewport (`current_focus` points at',
			'  the live one).',
			'- `.bh/mirror/<file>/adhd.yaml` \u2014 per-file reading aids: `highlight_keywords` and',
			'  read line-ranges (`read_paragraphs`).',
			'- `.bh/mirror/<path>/appearance.yaml` \u2014 user-selected visual presentation such as',
			'  the canvas card `background` preset.',
			'',
			'To answer or edit, start from the focused node. Its incoming `referenced_by` nodes',
			'are upstream context; follow either direction when more graph context is useful.',
			'Markdown links are ordinary navigation links and never create reference edges.',
			'To create a card, create its real user file or folder; a canvas card row stores only',
			'geometry.',
			'Only modify or create the user\'s own files when they explicitly ask.',
			'',
			'When asked, you can GENERATE or update these `.bh/` files from content, including',
			'creating references. Update both badge endpoints; the canvas derives the relation',
			'from that graph. Use `canvas.yaml` only for card geometry and edge endpoints/anchors.',
			'Match the existing YAML shape and read the latest version before editing so you',
			'don\'t overwrite what',
			'the app or user just wrote. `.bh/current_focus.yaml` is a symlink \u2014 never replace',
			'it with a regular file.',
			'',
			'For BaseHalf-specific workflows, use `.bh/agent-harness/index.md` as the',
			'progressive-disclosure index. Load only the matching scenario, such as focused-file',
			'rewrites, cursor/viewport questions, canvas workflows, or `.bh/` mirror writes,',
			'when that behavior matters.',
			'',
			'The user\'s files are the source of truth; `.bh/` is derived. Edit user files with',
			'your own tools; edit `.bh/` only on explicit request \u2014 otherwise the app owns it.',
			'`.bh/cache/` is gitignored and rebuildable;',
			'the rest of `.bh/` stays in git so the map travels with the folder.'
		]
	}
];
