/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Pointa Labs. All rights reserved.
 *  Licensed under the Apache License, Version 2.0. See LICENSE in the repository root.
 *--------------------------------------------------------------------------------------------*/

import '@xyflow/react/dist/base.css';
import './canvasReactVendor.css';
import {
	RiBold,
	RiCheckLine,
	RiFileCopyLine,
	RiFullscreenLine,
	RiH1,
	RiH2,
	RiH3,
	RiInformationLine,
	RiItalic,
	RiListOrdered,
	RiListUnordered,
	RiMoreLine,
	RiSubtractLine,
	RiText,
} from 'react-icons/ri';

// Keep Canvas contextual actions on the same icon vocabulary as the rich editor.
export const BaseHalfCanvasToolbarIcons = Object.freeze({
	heading1: RiH1,
	heading2: RiH2,
	heading3: RiH3,
	paragraph: RiText,
	bold: RiBold,
	italic: RiItalic,
	bulletList: RiListUnordered,
	orderedList: RiListOrdered,
	divider: RiSubtractLine,
	copy: RiFileCopyLine,
	copied: RiCheckLine,
	expand: RiFullscreenLine,
	information: RiInformationLine,
	more: RiMoreLine,
});

// Keep this façade explicit. The workbench loads this browser bundle by URL and
// consumes only these names; no bare React or React Flow imports may escape into
// VS Code's native ESM graph.
export {
	Children,
	Fragment,
	StrictMode,
	createContext,
	createElement,
	createRef,
	forwardRef,
	isValidElement,
	lazy,
	memo,
	startTransition,
	useCallback,
	useContext,
	useDeferredValue,
	useEffect,
	useId,
	useImperativeHandle,
	useLayoutEffect,
	useMemo,
	useReducer,
	useRef,
	useState,
	useSyncExternalStore,
	useTransition,
} from 'react';

export type {
	CSSProperties,
	ComponentProps,
	ComponentType,
	Context,
	DependencyList,
	Dispatch,
	ElementType,
	ForwardedRef,
	Key,
	MutableRefObject,
	PointerEvent as ReactPointerEvent,
	ReactElement,
	ReactNode,
	Ref,
	RefObject,
	SetStateAction,
} from 'react';

export { createRoot } from 'react-dom/client';
export type { Root, RootOptions } from 'react-dom/client';

export {
	Background,
	BackgroundVariant,
	BaseEdge,
	BezierEdge,
	ConnectionLineType,
	ConnectionMode,
	ControlButton,
	Controls,
	EdgeLabelRenderer,
	EdgeText,
	EdgeToolbar,
	Handle,
	MarkerType,
	MiniMap,
	NodeResizeControl,
	NodeResizer,
	NodeToolbar,
	PanOnScrollMode,
	Panel,
	Position,
	ReactFlow,
	ReactFlowProvider,
	ResizeControlVariant,
	SelectionMode,
	SimpleBezierEdge,
	SmoothStepEdge,
	StepEdge,
	StraightEdge,
	ViewportPortal,
	addEdge,
	applyEdgeChanges,
	applyNodeChanges,
	getBezierPath,
	getConnectedEdges,
	getIncomers,
	getNodesBounds,
	getOutgoers,
	getSmoothStepPath,
	getStraightPath,
	getViewportForBounds,
	reconnectEdge,
	useConnection,
	useEdges,
	useEdgesState,
	useHandleConnections,
	useInternalNode,
	useKeyPress,
	useNodeConnections,
	useNodeId,
	useNodes,
	useNodesData,
	useNodesInitialized,
	useNodesState,
	useOnSelectionChange,
	useOnViewportChange,
	useReactFlow,
	useStore,
	useStoreApi,
	useUpdateNodeInternals,
	useViewport,
} from '@xyflow/react';

export type {
	AriaLabelConfig,
	BackgroundProps,
	BaseEdgeProps,
	BuiltInEdge,
	BuiltInNode,
	Connection,
	ConnectionLineComponent,
	ConnectionLineComponentProps,
	ConnectionState,
	CoordinateExtent,
	DefaultEdgeOptions,
	Edge,
	EdgeChange,
	EdgeMouseHandler,
	EdgeProps,
	EdgeTypes,
	FinalConnectionState,
	FitViewOptions,
	HandleProps,
	HandleType,
	IsValidConnection,
	Node,
	NodeChange,
	NodeMouseHandler,
	NodeOrigin,
	NodeProps,
	NodeResizerProps,
	NodeTypes,
	OnConnect,
	OnEdgesChange,
	OnInit,
	OnMove,
	OnMoveEnd,
	OnMoveStart,
	OnNodeDrag,
	OnNodesChange,
	OnReconnect,
	OnSelectionChangeFunc,
	PanelProps,
	ReactFlowInstance,
	ReactFlowProps,
	Rect,
	ResizeControlProps,
	SelectionDragHandler,
	SnapGrid,
	UseNodesInitializedOptions,
	UseOnSelectionChangeOptions,
	UseOnViewportChangeOptions,
	Viewport,
	XYPosition,
} from '@xyflow/react';
